Repository Likelion-Hongik-Business-Project/ShinhanCard-FE, pull requests merged in 2025-08, with the labels that each got.

#30 [Feat] 수신함 컴포넌트 구현 / 404 페이지 구현
  src/App.tsx
  src/assets/svgs/inbox/bell.svg
  src/assets/svgs/inbox/check-box.svg
  src/assets/svgs/inbox/check.svg
  src/assets/svgs/inbox/comment.svg
  src/assets/svgs/inbox/inbox-bell.svg
  src/assets/svgs/inbox/inbox-box.svg
  src/assets/svgs/inbox/reset.svg
  src/assets/svgs/inbox/uncheck-box.svg
  src/assets/svgs/inbox/warning.svg
  src/assets/svgs/layout/home.svg
  src/assets/svgs/notFound/404.svg
  src/components/home/HomeMain.tsx
  src/components/inbox/Inbox.tsx
  src/components/inbox/InboxEmpty.tsx
  src/components/inbox/InboxItem.tsx
  src/components/inbox/InboxList.tsx
  src/components/inbox/InboxTabs.tsx
  src/components/inquiry/list/DateFilterModal.tsx
  src/components/inquiry/list/InquiryListItem.tsx
  src/components/inquiry/list/StatusFilterModal.tsx
  src/components/layout/Layout.tsx
  src/components/layout/sidebar/SideBar.tsx
  src/components/layout/sidebar/SideBarLargeItem.tsx
  src/components/layout/sidebar/SideBarSmallItem.tsx
  src/constants/inbox.ts
  src/hooks/useOutsideClick.ts
  src/mocks/inboxMock.ts
  src/pages/inbox/InboxPage.tsx
  src/pages/notFound/NotFoundPage.tsx
  src/styles/scrollbar.css
  src/types/inbox.ts
  src/utils/dateUtils.ts
  src/utils/formatDateToKorean.ts
  src/utils/inboxMapping.ts
  tsconfig.tsbuildinfo
Labels: ✨ Feature UI, 🎨 Design

#38 [Design] 화살표 이미지 통일 및 사이즈 조정 오류 해결
  src/assets/svgs/board/arrow.svg
  src/assets/svgs/board/index.ts
  src/assets/svgs/common/up.svg
  src/components/TeamBoard/FilterBar.tsx
  src/components/TeamBoard/InquiryItem.tsx
  src/components/TeamBoard/Pagination.tsx
  src/components/inquiry/form/SelectDropdown.tsx
  src/components/inquiry/list/InquiryListHeader.tsx
  src/components/layout/Layout.tsx
  src/components/layout/sidebar/SideBar.tsx
  tsconfig.tsbuildinfo
Labels: 🎨 Design, 🐞 BugFix

#29 [Feat] 추가문의 컴포넌트 구현
  src/assets/svgs/AdditionalInquiry/Bubble.svg
  src/assets/svgs/AdditionalInquiry/Enter.svg
  src/assets/svgs/AdditionalInquiry/FilledUnion.svg
  src/assets/svgs/AdditionalInquiry/Union.svg
  src/assets/svgs/AdditionalInquiry/UserProfile.svg
  src/assets/svgs/AdditionalInquiry/index.ts
  src/assets/svgs/common/pencil.svg
  src/components/AdditionalInquiry/AdditionalInquiryBody.tsx
  src/components/AdditionalInquiry/AdditionalInquiryForm.tsx
  src/components/AdditionalInquiry/AdditionalInquiryHeader.tsx
  src/components/AdditionalInquiry/AdditionalInquiryReplyForm.tsx
  src/components/AdditionalInquiry/AdditionalInquirySection.tsx
  src/components/AdditionalInquiry/AdditionalInquiryThread.tsx
  src/mocks/mockInquiryResponse.ts
  src/pages/inquiryDetail/InquiryDetailPage.tsx
  src/types/InquiryResponse.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature UI, 🎨 Design

#34 [Feat] 문의글 컴포넌트 기본상태 구현
  src/assets/svgs/inquiry/detail/bell-off.svg
  src/assets/svgs/inquiry/detail/bell-on.svg
  src/assets/svgs/inquiry/detail/bell.svg
  src/assets/svgs/inquiry/detail/check-gray.svg
  src/assets/svgs/inquiry/detail/check-green.svg
  src/assets/svgs/inquiry/detail/check.svg
  src/assets/svgs/inquiry/detail/pencil.svg
  src/assets/svgs/inquiry/detail/profile.svg
  src/assets/svgs/inquiry/detail/star-active.svg
  src/assets/svgs/inquiry/detail/star.svg
  src/assets/svgs/inquiry/detail/user-check.svg
  src/assets/svgs/inquiry/detail/users.svg
  src/components/AdditionalInquiry/AdditionalInquiryBody.tsx
  src/components/inquiry/detail/AssigneeActions.tsx
  src/components/inquiry/detail/AssigneeSection.tsx
  src/components/inquiry/detail/Header.tsx
  src/components/inquiry/detail/InquiryCard.tsx
  src/components/inquiry/detail/InquiryContent.tsx
  src/components/inquiry/detail/InquiryHeader.tsx
  src/components/inquiry/detail/NotificationButton.tsx
  src/components/inquiry/detail/PendingActions.tsx
  src/components/inquiry/detail/answer/AnswerEditor.tsx
  src/components/inquiry/detail/answer/AnswerItem.tsx
  src/components/inquiry/detail/answer/AnswerList.tsx
  src/components/inquiry/detail/answer/AnswerSection.tsx
  src/constants/inquiryStates.ts
  src/constants/userRoles.ts
  src/hooks/useInquiryState.ts
  src/mocks/mockInquiryDetailResponse.ts
  src/pages/inquiryDetail/InquiryDetailPage.tsx
  src/types/inquiryTypes.ts
  src/utils/dateUtils.ts
Labels: ✨ Feature UI, 🎨 Design

#40 [Feat] 로그인 API 연결 및 전역 상태 관리
  src/App.tsx
  src/apis/auth/authApi.ts
  src/apis/instance.ts
  src/apis/search/search.ts
  src/components/inbox/InboxItem.tsx
  src/components/login/IDInputField.tsx
  src/components/login/PasswordInputField.tsx
  src/components/router/RequireAuth.tsx
  src/hooks/auth/useAuth.ts
  src/hooks/auth/useAuthApi.ts
  src/hooks/useSearch.ts
  src/pages/login/LoginPage.tsx
  src/pages/notFound/NotFoundPage.tsx
  src/store/getAuthStore.ts
  src/store/useAuthStore.ts
  src/types/apiResponse.type.ts
  src/types/login/loginApi.type.ts
Labels: ♻️ Refactor, 📡 API

#39 [Feat] 노션 컴포넌트 타인 스페이스에 연결
  src/pages/userSpace/UserSpacePage.tsx
Labels: ✨ Feature UI, 🎨 Design

#57 [Feat] 내 담당 문의 / 내가 쓴 문의 / 스크랩 페이지 / 스크랩 / Excel API 연결
  src/apis/excel/excelApi.ts
  src/apis/inquiry/assigned/assignedApi.ts
  src/apis/inquiry/myQuestions/myQuestionsApi.ts
  src/apis/instance.ts
  src/apis/scrap/scrapApi.ts
  src/components/common/ExportDropdown.tsx
  src/components/inbox/InboxList.tsx
  src/components/inquiry/layout/InquiryPageLayout.tsx
  src/components/inquiry/list/DateFilterModal.tsx
  src/components/inquiry/list/InquiryList.tsx
  src/components/inquiry/list/InquiryListHeader.tsx
  src/components/inquiry/list/InquiryListItem.tsx
  src/components/inquiry/list/TeamTabButton.tsx
  src/components/inquiry/list/TeamTabs.tsx
  src/components/inquiry/list/TeamTabsModal.tsx
  src/constants/inquiry.ts
  src/hooks/excel/useExcelApi.ts
  src/hooks/inquiry/assigned/useAssignedApi.ts
  src/hooks/inquiry/myQuestions/useMyQuestionsApi.ts
  src/hooks/scrap/useScrap.ts
  src/hooks/scrap/useScrapApi.ts
  src/mocks/inquiryMock.ts
  src/mocks/myQuestionsMock.ts
  src/mocks/scrapMock.ts
  src/pages/assigned/AssignedPage.tsx
  src/pages/myQuestions/MyQuestionsPage.tsx
  src/pages/scrap/ScrapPage.tsx
  src/pages/userSpace/UserSpacePage.tsx
  src/styles/scrollbar.css
  src/types/excel/excelApi.type.ts
  src/types/inquiry/inquiryListApi.type.ts
  src/types/scrap/scrapApi.type.ts
  src/utils/dateUtils.ts
  src/utils/excelDownloadUtils.ts
  src/utils/inquiryStatus.ts
Labels: ♻️ Refactor, ✨ Feature UI, 🎨 Design, 📡 API

#50 [Feat] 소속 조회 api/ 문의글 작성 페이지 api 연동
  .pnp.cjs
  package.json
  src/apis/file/fileApi.ts
  src/apis/inquiry/draft/inquiryDraftApi.ts
  src/apis/inquiry/inquiryApi.ts
  src/apis/team/teamApi.ts
  src/components/common/Button.tsx
  src/components/common/ExportDropdown.tsx
  src/components/common/MarkdownViewer.tsx
  src/components/common/Modal.tsx
  src/components/inbox/Inbox.tsx
  src/components/inquiry/detail/answer/AnswerEditor.tsx
  src/components/inquiry/form/AssigneeSelector.tsx
  src/components/inquiry/form/DepartmentSelector.tsx
  src/components/inquiry/form/FileUploadBox.tsx
  src/components/inquiry/form/FileUploadItem.tsx
  src/components/inquiry/form/InquiryEditor.tsx
  src/components/inquiry/form/InquiryForm.tsx
  src/components/inquiry/form/InquiryFormModal.tsx
  src/components/inquiry/form/SelectDropdown.tsx
  src/components/inquiry/form/UserMultiSelectInput.tsx
  src/components/inquiry/form/UserSearchList.tsx
  src/components/inquiry/list/TeamTabs.tsx
  src/components/layout/sidebar/GroupSelector.tsx
  src/components/layout/sidebar/TeamSelector.tsx
  src/hooks/common/useDebounce.ts
  src/hooks/common/useOutsideClick.ts
  src/hooks/file/useDragAndDrop.ts
  src/hooks/file/useMultiFileUploader.ts
  src/hooks/file/useS3UploadFile.ts
  src/hooks/inquiry/create/useEditorImageUpload.ts
  src/hooks/inquiry/create/useInquiryDraft.ts
  src/hooks/inquiry/create/useInquiryDraftApi.ts
  src/hooks/inquiry/create/useInquiryFormState.ts
  src/hooks/inquiry/useEditor.ts
  src/hooks/inquiry/useInquiryApi.ts
  src/hooks/team/useDepartmentSelector.ts
  src/hooks/team/useOrganizationSelector.ts
  src/hooks/team/useTeamApi.ts
  src/hooks/useFakeProgress.ts
  src/hooks/useOrganizationSelector.ts
  src/mocks/groupTeamData.ts
  src/mocks/organizationMock.ts
  src/mocks/usersMock.ts
  src/pages/inquiry/InquiryFormPage.tsx
  src/styles/editor.css
  src/types/file/file.type.ts
  src/types/file/fileApi.type.ts
  src/types/inquiry/inquiryApi.type.ts
  src/types/inquiry/inquiryDraft.type.ts
  src/types/inquiry/inquiryDraftApi.type.ts
  src/types/team/teamApi.type.ts
  src/types/team/user.type.ts
  src/types/user.ts
  src/utils/s3UploadUtils.ts
  tsconfig.tsbuildinfo
  yarn.lock
Labels: 📡 API, 🐞 BugFix

#64 [Fix] 타입 에러 수정
  src/components/TeamBoard/InquiryItem.tsx
  src/components/TeamBoard/InquiryList.tsx
  src/mocks/mockTeamBoardResponse.ts
  src/types/teamInquires/teamInquiresApi.type.ts
Labels: 🐞 BugFix

#66 [Fix] is_scraped -> is_scrapped 로 필드명 변경
  src/apis/excel/excelApi.ts
  src/components/TeamBoard/InquiryItem.tsx
  src/components/TeamBoard/InquiryList.tsx
  src/components/inquiry/layout/InquiryPageLayout.tsx
  src/components/inquiry/list/InquiryList.tsx
  src/components/inquiry/list/InquiryListItem.tsx
  src/hooks/scrap/useScrapApi.ts
  src/pages/scrap/ScrapPage.tsx
  src/pages/userSpace/UserSpacePage.tsx
  src/types/excel/excelApi.type.ts
  src/types/inquiry/inquiryListApi.type.ts
Labels: 🐞 BugFix

#69 [Fix] team_id 로 useParams 받아오도록 수정
  src/pages/teamBoard/TeamBoardPage.tsx
Labels: 🐞 BugFix

#56 [Feat] 문의 상세 - 추가 문의 댓글 대댓글 api연결
  src/apis/comment/commentApi.ts
  src/apis/followup/followupApi.ts
  src/assets/svgs/followup/Bubble.svg
  src/assets/svgs/followup/Enter.svg
  src/assets/svgs/followup/FilledUnion.svg
  src/assets/svgs/followup/Union.svg
  src/assets/svgs/followup/UserProfile.svg
  src/assets/svgs/followup/index.ts
  src/components/AdditionalInquiry/AdditionalInquiryForm.tsx
  src/components/AdditionalInquiry/AdditionalInquiryReplyForm.tsx
  src/components/AdditionalInquiry/AdditionalInquirySection.tsx
  src/components/AdditionalInquiry/AdditionalInquiryThread.tsx
  src/components/Followup/FollowupBody.tsx
  src/components/Followup/FollowupCommentForm.tsx
  src/components/Followup/FollowupForm.tsx
  src/components/Followup/FollowupHeader.tsx
  src/components/Followup/FollowupSection.tsx
  src/components/Followup/FollowupThread.tsx
  src/hooks/inquiry/comment/useCommentApi.ts
  src/hooks/inquiry/followup/useFollowupApi.ts
  src/mocks/mockInquiryResponse.ts
  src/pages/inquiryDetail/InquiryDetailPage.tsx
  src/types/InquiryResponse.ts
  src/types/comment/commentApi.ts
  src/types/followup/followupApi.ts
  src/types/inquiryTypes.ts
Labels: ♻️ Refactor, 📡 API

#72 [Feat] 문의 상세페이지 api 연결, 오류 수정
  src/apis/inbox/inboxApi.ts
  src/apis/inquiry/detail/inquiryManagementApi.ts
  src/assets/svgs/inquiry/detail/users.svg
  src/components/common/LoadingSpinner.tsx
  src/components/common/Modal.tsx
  src/components/common/ProfileModal.tsx
  src/components/inquiry/detail/AssigneeActions.tsx
  src/components/inquiry/detail/AssigneeSection.tsx
  src/components/inquiry/detail/InquiryCard.tsx
  src/components/inquiry/detail/InquiryContent.tsx
  src/components/inquiry/detail/answer/AnswerItem.tsx
  src/components/inquiry/detail/answer/AnswerSection.tsx
  src/components/inquiry/form/InquiryFormModal.tsx
  src/components/layout/Layout.tsx
  src/hooks/home/useHomeMemberApi.ts
  src/hooks/inquiry/useInquiryApi.ts
  src/hooks/useInquiryDetail.ts
  src/hooks/useInquiryState.ts
  src/pages/assigned/AssignedPage.tsx
  src/pages/inquiry/InquiryFormPage.tsx
  src/pages/inquiryDetail/InquiryDetailPage.tsx
  src/pages/myQuestions/MyQuestionsPage.tsx
  src/pages/scrap/ScrapPage.tsx
  src/pages/teamBoard/TeamBoardPage.tsx
  src/styles/globals.css
  src/types/inquiry/inquiryManagementApi.type.ts
  src/types/inquiryTypes.ts
  tatus
Labels: ♻️ Refactor, 📡 API, 🐞 BugFix

#75 [Fix] 문의글 임시저장 오류 해결
  src/components/inquiry/detail/FileDownloadBox.tsx
  src/components/inquiry/detail/InquiryContent.tsx
  src/components/inquiry/detail/answer/AnswerItem.tsx
  src/components/inquiry/form/FileUploadItem.tsx
  src/hooks/file/useMultiFileUploader.ts
  src/hooks/inquiry/create/useInquiryDraft.ts
  src/hooks/team/useOrganizationSelector.ts
  src/pages/inquiry/InquiryFormPage.tsx
  src/types/file/file.type.ts
Labels: 📡 API, 🐞 BugFix

#77 fix: 추가문의 및 댓글 수정 권한 제한
  src/components/Followup/FollowupThread.tsx
Labels: 🐞 BugFix

#78 [Fix] 문의 상세 페이지 오류 수정
  src/hooks/inquiry/useAnswerApi.ts
  src/hooks/useInquiryDetail.ts
  src/hooks/useInquiryState.ts
Labels: 🐞 BugFix

#84 [Feat] 팀별 게시판 내에서 문의 작성 시 선택 팀으로 폼 초기값 세팅
  src/components/TeamBoard/layout/TeamBoardLayout.tsx
  src/hooks/team/useInitialOrgSelection.ts
  src/pages/inquiry/InquiryFormPage.tsx
Labels: 🐞 BugFix

#88 [Fix] TeamBoard 페이지 QA 반영
  src/components/TeamBoard/layout/TeamBoardLayout.tsx
  src/components/common/FilterBar.tsx
  src/components/inquiry/detail/InquiryHeader.tsx
  src/components/inquiry/layout/InquiryPageLayout.tsx
  src/components/inquiry/list/InquiryList.tsx
  src/hooks/teamInquires/useTeamInquiresApi.ts
  src/types/InquiryResponse.ts
  src/types/inquiry.ts
Labels: 🐞 BugFix

#91 [Fix] 문의글 상세 - 담당자 수정 시 검색 리스트 정렬
  src/components/inquiry/detail/AssigneeSection.tsx
  src/utils/userOrgUtils.ts
Labels: 🐞 BugFix

#100 [Fix] 문의글 작성 및 상세 오류 수정
  src/components/common/Modal.tsx
  src/components/inquiry/detail/answer/AnswerEditor.tsx
  src/components/inquiry/detail/answer/AnswerSection.tsx
  src/components/inquiry/form/FileUploadBox.tsx
  src/hooks/inquiry/create/useInquiryDraft.ts
  src/hooks/useInquiryDetail.ts
  src/utils/editorImageUtils.ts
  src/utils/markdownImageUtils.ts
Labels: 🐞 BugFix
